// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCVSl4kFuYNwtBRDja9Z-1x8vVnKd2K8o',
    appId: '1:97136137754:web:d4e9477280a4a1b2cde3a3',
    messagingSenderId: '97136137754',
    projectId: 'resmanageapp',
    authDomain: 'resmanageapp.firebaseapp.com',
    storageBucket: 'resmanageapp.firebasestorage.app',
    measurementId: 'G-LJGJ4BCSYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTIhXmQ1XZ4LER52eaiFxW_qdGf7_Z7k',
    appId: '1:97136137754:android:1458222f1ee58a22cde3a3',
    messagingSenderId: '97136137754',
    projectId: 'resmanageapp',
    storageBucket: 'resmanageapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehvBgl18GU-keOERxrwjWRFtT-gj21YE',
    appId: '1:97136137754:ios:527feed39205d6f6cde3a3',
    messagingSenderId: '97136137754',
    projectId: 'resmanageapp',
    storageBucket: 'resmanageapp.firebasestorage.app',
    iosBundleId: 'com.replib.churchapp',
  );
}
